### PR TITLE
Add deployment customization via deploy_steps

### PR DESCRIPTION
**Pull request by kirankt**
This PR adds support to customize baremetal deployment via Ironic's deploy_steps feature.

### CODE REVIEW

**Review by dtantsur — APPROVED** [review]
I'm quite sad we need to use JSON strings. I hope someone more familiar with Terraform can provide better ideas? Otherwise the patch LGTM.

**Comment by stbenjam** [comment]
Not sure why Travis tests aren't showing up on GitHub :-\

**Pull request merged**
